### ISSUE TITLE
Undefined constant warnings

### ISSUE THREAD

**Issue by raiwa** [gburton/Responsive-osCommerce#636] opened 2018-04-23 17:19 UTC
Warning: Use of undefined constant MODULE_HEADER_TAGS_BREADCRUMB_SCHEMA_TITLE - assumed 'MODULE_HEADER_TAGS_BREADCRUMB_SCHEMA_TITLE' (this will throw an Error in a future version of PHP) in C:\xampp_php_7_2\htdocs\BS_edge_2018_04_20\includes\modules\header_tags\ht_breadcrumb_schema.php on line 22

Warning: Use of undefined constant MODULE_HEADER_TAGS_BREADCRUMB_SCHEMA_DESCRIPTION - assumed 'MODULE_HEADER_TAGS_BREADCRUMB_SCHEMA_DESCRIPTION' (this will throw an Error in a future version of PHP) in C:\xampp_php_7_2\htdocs\BS_edge_2018_04_20\includes\modules\header_tags\ht_breadcrumb_schema.php on line 23

Warning: Use of undefined constant MODULE_CONTENT_I_TITLE_TITLE - assumed 'MODULE_CONTENT_I_TITLE_TITLE' (this will throw an Error in a future version of PHP) in C:\xampp_php_7_2\htdocs\BS_edge_2018_04_20\includes\modules\content\index\cm_i_title.php on line 25

Warning: Use of undefined constant MODULE_CONTENT_I_TITLE_DESCRIPTION - assumed 'MODULE_CONTENT_I_TITLE_DESCRIPTION' (this will throw an Error in a future version of PHP) in C:\xampp_php_7_2\htdocs\BS_edge_2018_04_20\includes\modules\content\index\cm_i_title.php on line 26

Warning: Use of undefined constant MODULE_CONTENT_I_TITLE_PUBLIC_TITLE - assumed 'MODULE_CONTENT_I_TITLE_PUBLIC_TITLE' (this will throw an Error in a future version of PHP) in C:\xampp_php_7_2\htdocs\BS_edge_2018_04_20\includes\modules\content\index\templates\tpl_cm_i_title.php on line 4
MODULE_CONTENT_I_TITLE_PUBLIC_TITLE

**Comment by gburton** [comment] 2018-04-30 17:24
> Warning: Use of undefined constant MODULE_HEADER_TAGS_BREADCRUMB_SCHEMA_DESCRIPTION - assumed 'MODULE_HEADER_TAGS_BREADCRUMB_SCHEMA_DESCRIPTION' (this will throw an Error in a future version of PHP) in C:\xampp_php_7_2\htdocs\BS_edge_2018_04_20\includes\modules\header_tags\ht_breadcrumb_schema.php on line 23

Same:
https://github.com/gburton/Responsive-osCommerce/search?utf8=%E2%9C%93&q=MODULE_HEADER_TAGS_BREADCRUMB_SCHEMA_DESCRIPTION&type=

**Comment by gburton** [comment] 2018-04-30 17:25
> Warning: Use of undefined constant MODULE_CONTENT_I_TITLE_PUBLIC_TITLE - assumed 'MODULE_CONTENT_I_TITLE_PUBLIC_TITLE' (this will throw an Error in a future version of PHP) in C:\xampp_php_7_2\htdocs\BS_edge_2018_04_20\includes\modules\content\index\templates\tpl_cm_i_title.php on line 4

Same:
https://github.com/gburton/Responsive-osCommerce/search?utf8=%E2%9C%93&q=MODULE_CONTENT_I_TITLE_PUBLIC_TITLE&type=

**Comment by Kymation** [comment] 2018-04-30 17:50
All of the title and description constants throw warnings in the Admin when the module is not installed. They annoyed me so I've been fixing them. I can try to get Github to send the fixes to you if you want them.

**Comment by raiwa** [comment] 2018-04-30 17:56
It's like @Kymation says, also all uninstalled payment modules throw these errors.

**Comment by gburton** [comment] 2018-04-30 19:38
I can't recreate it.  No warnings at all...

**Comment by BrockleyJohn** [comment] 2018-04-30 19:40
on php7.2?

**Comment by BrockleyJohn** [comment] 2018-04-30 20:26
hmm, I get 
`Notice: Undefined variable: SID in /...admin/includes/functions/html_output.php on line 48` (lots of times)
on the uninstalled payment modules list. 
Admittedly this isn't a totally up to date installation.

**Comment by raiwa** [comment] 2018-05-01 15:00
SID reported here:
https://github.com/gburton/Responsive-osCommerce/issues/626
and I reported it about one year ago with push of fix.

**Comment by gburton** [comment] 2018-05-02 16:39
The only one I can see is SID, all the others do not present themselves :-\

**Comment by raiwa** [comment] 2018-05-02 18:50
Some more warnings/notice on vanillastore latest version under php7.2 and error reporting all:

Index category level product listing:
Notice: Undefined variable: currency in C:\xampp_php_7_2\htdocs\BS_edge_2018_04_20\includes\modules\product_listing.php on line 170

product info, product with attributes:
Notice: Undefined variable: product_info in C:\xampp_php_7_2\htdocs\BS_edge_2018_04_20\includes\modules\content\product_info\cm_pi_options_attributes.php on line 61

shopping cart, paypal app not installed:
Warning: Use of undefined constant OSCOM_APP_PAYPAL_GATEWAY - assumed 'OSCOM_APP_PAYPAL_GATEWAY' (this will throw an Error in a future version of PHP) in C:\xampp_php_7_2\htdocs\BS_edge_2018_04_20\includes\modules\payment\paypal_express.php on line 73

**Comment by BrockleyJohn** [comment] 2018-05-02 21:35
paypal_express shopping_cart fix here https://github.com/gburton/Responsive-osCommerce/pull/649

**Comment by gburton** [comment] 2018-05-02 21:53
@BrockleyJohn is 649 due to Paypal Express being half installed (in the installation script) ?

**Comment by BrockleyJohn** [comment] 2018-05-03 07:05
@gburton it's likely for a new install. There is code in the constructor for diverting shopping_cart and checkout_payment that gets executed whether the module is enabled or not; this is where the notices are thrown (because the app isn't installed but presumably ppexpress is in the list of installed payment modules).
It won't fix it for similar circumstances created by the shopowner, eg copying the paypal app in while upgrading an earlier version where paypal express was installed but not enabled.
It is also likely that the code gets executed when the app is properly installed and ppexpress is installed but not enabled (which I think happens by default when you install the app but don't want express).
However, while wrong there is negligible impact.

**Comment by gburton** [comment] 2018-05-03 10:30
https://github.com/gburton/Responsive-osCommerce/commit/44583b68d014a4a3bd5302ff5fb9806cf3d9eaa5
https://github.com/gburton/Responsive-osCommerce/commit/2edd32d16a260b723a513ca07daeb7b44d325fea

**Comment by JAValeryon** [comment] 2018-05-08 12:12
Hi, I get undefined constant warnings when trying to install or uninstall many of the payment modules. 

For example: 

 Warning: Use of undefined constant MODULE_PAYMENT_AUTHORIZENET_CC_AIM_TEXT_TITLE - assumed 'MODULE_PAYMENT_AUTHORIZENET_CC_AIM_TEXT_TITLE' (this will throw an Error in a future version of PHP) in /home/vagrant/code/dev/includes/modules/payment/authorizenet_cc_aim.php on line 23

It looks like the language file is not being included, in fact, If I add the following line 

`include($module_language_directory .$language.'/modules/'.$module_type.'/'. $class . $file_extension);`

into modules.php the issue is solved but I don't know if this could be a correct fix or if the problem is somewhere else

```
      case 'remove':
        $file_extension = substr($PHP_SELF, strrpos($PHP_SELF, '.'));
        $class = basename($_GET['module']);
        if (file_exists($module_directory . $class . $file_extension)) {
          include($module_language_directory .$language.'/modules/'.$module_type.'/'. $class . $file_extension);
          include($module_directory . $class . $file_extension);
          $module = new $class;
          if ($action == 'install') {
            if ($module->check() > 0) { // remove module if already installed
              $module->remove();
            }

```

**Comment by gburton** [comment] 2018-05-08 12:15
@JAValeryon what is your PHP version (exact version please) also what is your error_reporting set to ?

**Comment by JAValeryon** [comment] 2018-05-08 14:05
PHP version = 7.2.3-1+ubuntu16.04.1+deb.sury.org+1
error_reporting set to : E_ALL & ~E_DEPRECATED & ~E_NOTICE

**Comment by gburton** [comment] 2018-05-08 14:06
great, thank you.  I think your language fix is good so https://github.com/gburton/Responsive-osCommerce/pull/664/commits/b3f5907906a78ff6395695d22b76e7485233cea1

**Comment by gburton** [comment] 2018-05-08 14:07
does anyone see more undefined problems anywhere?

**Closed** 2018-05-10 08:08 UTC
