### ISSUE TITLE
Obsolete new_products module in \includes\modules\

### ISSUE THREAD

**Issue by Moxamint** [gburton/Responsive-osCommerce#375] opened 2016-05-14 23:46 UTC
Now we have a new content module 'new_products' in <<\includes\modules\content\index>> for index page.  Shouldn't we delete file <<\includes\modules\new_products.php>> and remove its reference in <<\index.php>>?

The following line of code in <<\index.php>>, line 104, throws an error when browsing to sub-category:

  `<?php include(DIR_WS_MODULES . FILENAME_NEW_PRODUCTS); ?>`

Error message:

  `1327 - Undeclared variable: MAX_DISPLAY_NEW_PRODUCTS`

where the named variable I believe has been removed from configuration values of the latest repo.  Also, maybe <<\includes\modules\upcoming_products.php>> should be dealt with as well?  Although I don't see it causing any issues yet.

**Comment by BrockleyJohn** [comment] 2016-05-15 06:45
@Moxamint I think my test system for the index nested update doesn't throw this error - please see if you can reproduce on [http://bromleybr.co.uk/bs234/](url)

This was a clean install to test the installer as well as the code

**Comment by BrockleyJohn** [comment] 2016-05-15 06:48
Sorry - just realised it's because you've changed error reporting in application_top

**Comment by BrockleyJohn** [comment] 2016-05-15 07:10
@Moxamint that site now has E_ALL and is running php5.6 - and I still can't reproduce. Would you try?

**Comment by Moxamint** [comment] 2016-05-15 07:11
@BrockleyJohn The two instances of MAX_DISPLAY_NEW_PRODUCTS in <<\includes\modules\new_products.php>> simply don't exist in configuration values, thus the error.

**Comment by BrockleyJohn** [comment] 2016-05-15 07:11
I don't get an error

**Comment by Moxamint** [comment] 2016-05-15 07:17
You don't get the error if you have MAX_DISPLAY_NEW_PRODUCTS left over in your configuration data table.  Please do a search for MAX_DISPLAY_NEW_PRODUCTS in <<\install\oscommerce.sql>> from the latest repo and you'll see what I mean.

**Comment by BrockleyJohn** [comment] 2016-05-15 07:19
1. This is a clean install
2. My index.php does not include this module

I don't think the problem is in the core. I think it's in your test system.
While I agree the old module is probably not required, since it's not used it can't throw an error.

**Comment by Moxamint** [comment] 2016-05-15 07:32
Sorry but I am confused.  I downloaded the whole zipped package and did complete file comparisons.  This line of code <?php include(DIR_WS_MODULES . FILENAME_NEW_PRODUCTS); ?> IS in index.php from the latest package.

Am I doing something wrong?

**Comment by BrockleyJohn** [comment] 2016-05-15 07:37
Apparently so. What whole zipped package did you download? I thought they were only available for releases...

I pull changes into a local repo on Sourcetree to test them

**Comment by Moxamint** [comment] 2016-05-15 07:43
There is a big fat "Download ZIP" button underneath contributors link...
![image 2](https://cloud.githubusercontent.com/assets/11028615/15272683/caa075e6-1ab3-11e6-9c14-fc47b3a94587.png)

**Comment by BrockleyJohn** [comment] 2016-05-15 07:55
Ah - ok - that's presumably the latest edge, which may have the error you're experiencing.

My test system is Gary's latest pull request for index nested.

It appears the problem you're reporting is fixed in that. If the zip is what I think, then you won't see the fix there until Gary merges the pull request into core which he talked about doing after the weekend.

You can see the changes here:
[https://github.com/gburton/Responsive-osCommerce/pull/373](url)

but I don't know of an easy way to download the changed files without using a desktop repo

**Comment by Moxamint** [comment] 2016-05-15 08:09
OK thanks.  I think I'll just wait until all fixes are merged.  Thanks again.

**Comment by BrockleyJohn** [comment] 2016-05-15 08:27
@Moxamint actually, I think there's a way to download a zip of the whole thing including the changes for index nested...
On the page where you were before, change the branch in the drop-down on the left to Modular-Index-Nested
Then when you hit download zip, you should get the same thing as me going via a desktop repo

**Comment by Moxamint** [comment] 2016-05-15 08:39
Yes it does - thanks again for the tip!

**Closed** 2016-05-15 09:22 UTC
